name: todo_app
description: A new Flutter project.

publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  easy_date_timeline: 1.0.2  # Downgrade here
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  flutter_easyloading: ^3.0.5
  bot_toast: ^4.1.3
  flutter_slidable: ^3.1.1
  firebase_auth: ^4.16.0
  animated_custom_dropdown: ^3.1.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf