// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfXCoomCMyB6XaJ_IkGDprqFo4d2s0M-8',
    appId: '1:80779331670:web:abc2cd7cb142dc5af693f7',
    messagingSenderId: '80779331670',
    projectId: 'to-do-app-b8e8e',
    authDomain: 'to-do-app-b8e8e.firebaseapp.com',
    storageBucket: 'to-do-app-b8e8e.appspot.com',
    measurementId: 'G-GYZ37RE5W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsygpcXx4gdIxc7CRud7WgimfaSmYkn30',
    appId: '1:80779331670:android:618f11e0570b7616f693f7',
    messagingSenderId: '80779331670',
    projectId: 'to-do-app-b8e8e',
    storageBucket: 'to-do-app-b8e8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPco2iQp8fcNwjUX_wGQyUU5dYKYZem0c',
    appId: '1:80779331670:ios:9cb7cfee53beb8e2f693f7',
    messagingSenderId: '80779331670',
    projectId: 'to-do-app-b8e8e',
    storageBucket: 'to-do-app-b8e8e.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPco2iQp8fcNwjUX_wGQyUU5dYKYZem0c',
    appId: '1:80779331670:ios:9cb7cfee53beb8e2f693f7',
    messagingSenderId: '80779331670',
    projectId: 'to-do-app-b8e8e',
    storageBucket: 'to-do-app-b8e8e.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfXCoomCMyB6XaJ_IkGDprqFo4d2s0M-8',
    appId: '1:80779331670:web:28b0f5b8626839cdf693f7',
    messagingSenderId: '80779331670',
    projectId: 'to-do-app-b8e8e',
    authDomain: 'to-do-app-b8e8e.firebaseapp.com',
    storageBucket: 'to-do-app-b8e8e.appspot.com',
    measurementId: 'G-0D9BWDHZ3X',
  );

}